unique_ids:
  forms:
    Form1: 7WUHGWJ5UNLCWCB73RK6NKXZIKYY4EAE
  modules: {}
  server_modules:
    ServerModule1: CICQ5HKVASQ7YJTU26XWTGXSPNU3OKWS
  assets:
    standard-page.html: OI5R6XUYZOPLSW46UWNCSOD3N2RNXPNM
    theme.css: VLNM2PGNO4OPSSMH3D3VSHDBRZ5OPVIC
